### ISSUE TITLE
[Internal] [Feature] Separate Out Metadata Split Process

### ISSUE THREAD

**Issue by ankushkgupta2** [CDCgov/tostadas#130]
**What is the Feature Related To? Please Provide a Description.**
Separate out process for metadata splitting, to be called before submission during the submission entrypoints. This way, the user can pass in a multi-sample metadata file, and it will detect this + split it for them. 

Metadata validation needs to be adapted to feed into this new process (keeps entire excel intact and only separates at this new process). 

**Place an :x: in a Box that Best Matches the Feature's Importance:**
* [] **1** - Most important (absolutely integral and will not use codebase at all without it)
* [X] **2-4** - Moderate (still using codebase for other functions but is serving as a blocker for future use-cases)
* [] **5** - Least important (would like to see but there are no stringent expectations nor urgency for current/future use-cases)&nbsp;

**Any Additional Context or Information? Has There Been Any Progress Made So Far Towards this Request? Any Helpful Resources to Reference? Screenshots or Links?**
N/A

**Comment by kyleoconnell** [comment]
Issue was solved by always running validate_metadata before running submission.
