### ISSUE TITLE
[Internal] [Bug] GISAID Submission Error 

### ISSUE THREAD

**Issue by ankushkgupta2** [CDCgov/tostadas#132]
**What is the Bug Related To? Please Provide a Description.**&nbsp;  
Receiving an error when attempting to do a test submission to GISAID. It is looking for some authentication file that it cannot find. 

**Place an :x: in a Box that Best Matches the Bug's Importance:**
* [X] **1** - Most severe (a full-break in core function)
* [] **2-4** - Moderate (break for a particular aspect/feature) (how integral is the broken feature?)
* [] **5** - Least severe (non-functional issue, such as inconsitency / error in documentation or administrative in nature)&nbsp;

**Please Complete the Following Information:**
 - OS: [e.g. iOS]: N/A
 - Browser [e.g. chrome, safari]: N/A
 - Version [e.g. 22]: N/A
 - Run environment (container, cloud service, HPC, platform, etc.): Scicomp

 **Please Outline Necessary Steps to Replicate Bug (Go to.. Click on... Install the following... etc.):**
N/A

**Any Additional Context or Information? Has There Been Any Progress Made So Far Towards this Request? Any Concrete Instructions to Resolve the Bug or Helpful Resources to Reference? Screenshots or Logs?**
![image](https://github.com/CDCgov/tostadas/assets/107437419/2f546276-256a-479d-a0ca-863505c8e957)

**Comment by jessicarowell** [comment]
Closing because this whole piece will be rewritten (probably for v4.2.0)

**Comment by jessicarowell** [comment]
Closing because this whole piece will be rewritten (probably for v4.2.0)
