### ISSUE TITLE
[Internal] [Test] Test Out Raw Reads (FASTQ) and .GZ Files 

### ISSUE THREAD

**Issue by ankushkgupta2** [CDCgov/tostadas#133]
**Please Provide a Description of the Testing Request.**
Need to test out user pointing to a single .GZ fasta file:
- unzips it 
- assigns the paths in the metadata file to sample with matching name, if cannot be found, throws an error

Need to test out .FASTQ formatted file

**Place an :x: in a Box that Best Matches the Test Request's Importance:**
* [] **1** - Urgent (absolutely integral and core-functionlaity of the codebase is completely compromised without this test)
* [X] **2** - Most Important (codebase can be used for some core-functions but the test needs to be executed for some)
* [] **3-4** - Moderate (codebase can be used for all core-functions but the test needs to be exexcuted for some other ones)
* [] **5** - Least important (would like to see but there are no stringent expectations nor urgency for current/future use-cases)&nbsp;

**Any Additional Context or Information? Has There Been Any Progress Made So Far Towards this Request? Any Helpful Resources to Reference? Screenshots or Links?**
N/A

**Comment by jessicarowell** [comment]
Closed because pipeline has been significantly refactored since this time
