### ISSUE TITLE
[Internal] [Feature] Enhance Metadata Validation

### ISSUE THREAD

**Issue by ankushkgupta2** [CDCgov/tostadas#138]
**What is the Feature Related To? Please Provide a Description.**
Need to enhance capability for metadata validation to do the following (based on findings during beta testing):
- cases where a value for 'collection_date' is provided that does not contain dashes in it, need to be recorded in the error log + potential program stoppage (need to double check if this formatting is required for certain NCBI databases)
- the 'host' field needs to be checked and populated with 'not included' if empty 

**Place an :x: in a Box that Best Matches the Feature's Importance:**
* [] **1** - Most important (absolutely integral and will not use codebase at all without it)
* [X] **2-4** - Moderate (still using codebase for other functions but is serving as a blocker for future use-cases)
* [] **5** - Least important (would like to see but there are no stringent expectations nor urgency for current/future use-cases)&nbsp;

**Any Additional Context or Information? Has There Been Any Progress Made So Far Towards this Request? Any Helpful Resources to Reference? Screenshots or Links?**
N/A

**Comment by jessicarowell** [comment]
This will be resolved with the update to metadata validation steps
