### ISSUE TITLE
[Internal] [Feature]  Check metadata date format

### ISSUE THREAD

**Issue by kyleoconnell** [CDCgov/tostadas#154]
Is the data supposed to be 2022-06 or an it handle including the day?

**Place an :x: in a Box that Best Matches the Feature's Importance:**
* [] **1** - Most important (absolutely integral and will not use codebase at all without it)
* [X] **2-4** - Moderate (still using codebase for other functions but is serving as a blocker for future use-cases)
* [] **5** - Least important (would like to see but there are no stringent expectations nor urgency for current/future use-cases)&nbsp;

**Any Additional Context or Information? Has There Been Any Progress Made So Far Towards this Request? Any Helpful Resources to Reference? Screenshots or Links?**

**Comment by jessicarowell** [comment]
This will be resolved by 1) rewriting the submission code, and 2) updating the metadata validation
