### ISSUE TITLE
[External] [Feature] Clarify Conda Requirement

### ISSUE THREAD

**Issue by garfinjm** [CDCgov/tostadas#199]
Hello,

I'm interested in using tostadas in a multi-user environment that isn't very conda friendly. If Nextflow + Apptainer are already available in my environment is it still necessary to have conda available?

**Place an :x: in a Box that Best Matches the Feature's Importance:**
* [] **1** - Most important (absolutely integral and will not use codebase at all without it)
* [] **2-4** - Moderate (still using codebase for other functions but is serving as a blocker for future use-cases)
* [ :x: ] **5** - Least important (would like to see but there are no stringent expectations nor urgency for current/future use-cases)&nbsp;

**Comment by jessicarowell** [comment]
Sorry for the enormous delay on this.

But no you do not need conda, you can run it with docker or singularity using `-profile docker` or `-profile singularity`.
