### ISSUE TITLE
[Internal] [Bug] Vadr missing from conda profile

### ISSUE THREAD

**Issue by jessicarowell** [CDCgov/tostadas#222]
When running with `profile conda`, vadr is missing.  Needs to be added to `environment.yml`. 

**Place an :x: in a Box that Best Matches the Bug's Importance:**
* [] **1** - Most severe (a full-break in core function)
* [x] **2-4** - Moderate (break for a particular aspect/feature) (how integral is the broken feature?)
* [] **5** - Least severe (non-functional issue, such as inconsitency / error in documentation or administrative in nature)&nbsp;

**Please Complete the Following Information:**
 - OS: [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Version [e.g. 22]:
 - Run environment (container, cloud service, HPC, platform, etc.):

 **Please Outline Necessary Steps to Replicate Bug (Go to.. Click on... Install the following... etc.):**
`nextflow run main.nf -profile test,conda --species rsv --annotation --submission --sra --biosample --genbank --output_dir test_rsv --submission_config ~/02.scratch/submission_config.yaml`

**Any Additional Context or Information? Has There Been Any Progress Made So Far Towards this Request? Any Concrete Instructions to Resolve the Bug or Helpful Resources to Reference? Screenshots or Logs?**

Nextflow 24.10.0 is available - Please consider updating your version to it

 N E X T F L O W   ~  version 24.04.2

Launching `main.nf` [trusting_venter] DSL2 - revision: 92b49e04b8

executor >  local (4)
[8a/40950f] process > TOSTADAS_WORKFLOW:TOSTADAS:VALIDATE_PARAMS                      [100%] 1 of 1 ✔
[c5/940c17] process > TOSTADAS_WORKFLOW:TOSTADAS:METADATA_VALIDATION                  [100%] 1 of 1 ✔
[56/965e75] process > TOSTADAS_WORKFLOW:TOSTADAS:RUN_VADR:VADR_TRIM (1)               [100%] 1 of 1, failed: 1 ✘
[-        ] process > TOSTADAS_WORKFLOW:TOSTADAS:RUN_VADR:VADR_ANNOTATION             -
[-        ] process > TOSTADAS_WORKFLOW:TOSTADAS:RUN_VADR:VADR_POST_CLEANUP           -
[26/d90d2c] process > TOSTADAS_WORKFLOW:TOSTADAS:GET_WAIT_TIME                        [100%] 1 of 1 ✔
[-        ] process > TOSTADAS_WORKFLOW:TOSTADAS:INITIAL_SUBMISSION:SUBMISSION        -
[-        ] process > TOSTADAS_WORKFLOW:TOSTADAS:INITIAL_SUBMISSION:WAIT              -
[-        ] process > TOSTADAS_WORKFLOW:TOSTADAS:INITIAL_SUBMISSION:UPDATE_SUBMISSION -
ERROR ~ Error executing process > 'TOSTADAS_WORKFLOW:TOSTADAS:RUN_VADR:VADR_TRIM (1)'

Caused by:
  Process `TOSTADAS_WORKFLOW:TOSTADAS:RUN_VADR:VADR_TRIM (1)` terminated with an error exit status (127)

Command executed:

  fasta-trim-terminal-ambigs.pl         --minlen 50         --maxlen 210000         MZ568967.fasta >         DRR152972.trimmed.fasta

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: fasta-trim-terminal-ambigs.pl: command not found

Work dir:
  /scicomp/scratch/ick4/56/965e7502270e10d2a833fbc12f3cbd

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details

**Comment by RamiyapriyaS** [comment]
Added a VADR conda environment.
