### ISSUE TITLE
[Internal] [Bug] Remove Required GFF Path for SRA Submission

### ISSUE THREAD

**Issue by ankushkgupta2** [CDCgov/tostadas#43]
**What is the Bug Related To? Please Provide a Description.**&nbsp;  
Currently, the prep_submission module (under modules/submission_entrypoints/) requires a valid submission_only_gff path, but SRA only submission does not need GFF files. It needs to be adapted to take into consideration the submission_database parameter (whether SRA or not) and then adjust for passed in params/preparation accordingly. 

**Categorize the Severity of the Bug from 1-5:** **1**
* 1 = most severe (a full-break in core function)
* 2-4 = moderate (break for a particular aspect/feature) (how integral is the broken feature?)
* 5 = least severe (non-functional issue, such as inconsistency / error in documentation or administrative in nature)&nbsp;   

**Please Complete the Following Information:**
 - OS: [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Version [e.g. 22]:
 - Run environment (container, cloud service, HPC, platform, etc.):

 **Please Outline Necessary Steps to Replicate Bug (Go to.. Click on... Install the following... etc.):**

**Any Additional Context or Information? Has There Been Any Progress Made So Far Towards this Request? Any Concrete Instructions to Resolve the Bug or Helpful Resources to Reference? Screenshots or Logs?**

**Comment by ankushkgupta2** [comment]
@mollymitchell70 Hey Molly, feel free to fill out some of the fields in the issue template above (info on the environment it was being ran in + both of the errors that we had seen). Thanks!

**Comment by mollymitchell70** [comment]
Hi Ankush, 

Of course, and thank you for your help earlier today and for fixing this.

What is the Bug Related To? Please Provide a Description. 
Currently, the prep_submission module (under modules/submission_entrypoints/) requires a valid submission_only_gff path, but SRA only submission does not need GFF files. It needs to be adapted to take into consideration the submission_database parameter (whether SRA or not) and then adjust for passed in params/preparation accordingly.

Categorize the Severity of the Bug from 1-5: 1

1 = most severe (a full-break in core function)
2-4 = moderate (break for a particular aspect/feature) (how integral is the broken feature?)
5 = least severe (non-functional issue, such as inconsistency / error in documentation or administrative in nature) 
Please Complete the Following Information:

OS: [e.g. iOS]: Linux
Browser [e.g. chrome, safari]: Edge or Chrome
Version [e.g. 22]: 22
Run environment (container, cloud service, HPC, platform, etc.): HPC, singularity/apptainer
Please Outline Necessary Steps to Replicate Bug (Go to.. Click on... Install the following... etc.):

command: 
nextflow run main.nf -profile conda -entry only_initial_submission -params-file $PWD/params/standard.yml

Submit only to sra without .gff and with multiple .fastq.gz

Any Additional Context or Information? Has There Been Any Progress Made So Far Towards this Request? Any Concrete Instructions to Resolve the Bug or Helpful Resources to Reference? Screenshots or Logs?
