### ISSUE TITLE
[Internal] [Feature] Bakta Integration

### ISSUE THREAD

**Issue by ankushkgupta2** [CDCgov/tostadas#48]
**What is the Feature Related To? Please Provide a Description.**
https://mstdn.science/@oschwengers/110463390271389048

**Categorize the Importance of the Feature from 1-5:**
* 1 = most important (absolutely integral and codebase usage might be hindered significantly)
* 2-4 = moderate (expect some codebase usage for other functions but may be serving as a blocker for specific user use-cases)
* 5 = least important (would like to see but there are no stringent expectations or urgency for expected user use-cases)  

**Rating:** 5

**Any Additional Context or Information? Has There Been Any Progress Made So Far Towards this Request? Any Helpful Resources to Reference? Screenshots or Links?**
N/A

**Comment by ankushkgupta2** [comment]
Linked to Issues #61 / #60 / #58

**Comment by ankushkgupta2** [comment]
Need to test the following cases:
(1) FASTA is not present/specified only reads 
(2) FASTA is present with reads

**Comment by Swarnali3** [comment]
Integrated bakta with Tostadas. Bakta runs with a test config file for bacteria (test_bacteria_params.config). Currently, the workflow is designed to run with a single fasta file (may/may not have multiple contigs). The output is a reformatted gff file, a fasta file of the sample and a tbl file for submission via table2asn.
