### ISSUE TITLE
[Internal] [Feature] Add Expected Bacterial Fields in Metadata 

### ISSUE THREAD

**Issue by ankushkgupta2** [CDCgov/tostadas#60]
**What is the Feature Related To? Please Provide a Description.**
Explore and implement certain core fields that are checked during metadata validation for bacterial samples only. 

Potentially the following so far:
- serotype (for Biosample)
- sequence type (for Biosample)
- toxigenicity (for Biosample)

**Place an :x: in a Box that Best Matches the Feature's Importance:**
* [X] **1** - Most important (absolutely integral and will not use codebase at all without it)
* [] **2-4** - Moderate (still using codebase for other functions but is serving as a blocker for future use-cases)
* [] **5** - Least important (would like to see but there are no stringent expectations nor urgency for current/future use-cases)&nbsp;

**Any Additional Context or Information? Has There Been Any Progress Made So Far Towards this Request? Any Helpful Resources to Reference? Screenshots or Links?**
N/A

**Comment by jessicarowell** [comment]
This will be included as custom fields when users can choose their own biosample package
