### ISSUE TITLE
[Internal] [Bug] Error with Processing Single Sequence

### ISSUE THREAD

**Issue by jtakakuwa** [CDCgov/tostadas#90]
**What is the Bug Related To? Please Provide a Description.**&nbsp;  
When running a single fasta sequence and gff file through the -only_initial_submission step in Tostadas, an error is produced that prevents any further output. 

This error is corrected by adding another fasta sequence to the initial input and another gff file to the liftoff_output. This error does not occur in the older version of Tostadas (/scicomp/groups-pure/Projects/scbs_mpob/repos/mpxv_annotation_submission_dev/main.nf). 

**Place an :x: in a Box that Best Matches the Bug's Importance:**
* [X] **1** - Most severe (a full-break in core function)
* [] **2-4** - Moderate (break for a particular aspect/feature) (how integral is the broken feature?)
* [] **5** - Least severe (non-functional issue, such as inconsitency / error in documentation or administrative in nature)&nbsp;

**Please Complete the Following Information:**
 - OS: [e.g. iOS]: N/A
 - Browser [e.g. chrome, safari]: N/A
 - Version [e.g. 22]: N/A 
 - Run environment (container, cloud service, HPC, platform, etc.): Rosalind cluster, with the mpxv_annotation_submission_dev environment

 **Please Outline Necessary Steps to Replicate Bug (Go to.. Click on... Install the following... etc.):**

Path to files: /scicomp/groups-pure/Projects/scbs_mpob/incoming_data/20231205-0030/

Nextflow command: 
nextflow run /scicomp/groups-pure/Projects/scbs_mpob/repos/tostadas/main.nf -profile conda -params-file /scicomp/groups-pure/Projects/scbs_mpob/incoming_data/20231205-0030/params.yml -entry only_initial_submission

Error produced: 
Error executing process > 'only_initial_submission:RUN_INITIAL_SUBMISSION:SUBMISSION (1)'

Caused by:
  Process `only_initial_submission:RUN_INITIAL_SUBMISSION:SUBMISSION` input file name collision -- There are multiple input files for each of the following file names: 20231205-0030

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Any Additional Context or Information? Has There Been Any Progress Made So Far Towards this Request? Any Concrete Instructions to Resolve the Bug or Helpful Resources to Reference? Screenshots or Logs?**

![Screenshot (19)](https://github.com/CDCgov/tostadas/assets/90364063/5cf230ae-9ac4-49bd-93e3-594dab9b76ac)

**Comment by jessicarowell** [comment]
I believe this was fixed. This is a very old issue that Ankush assigned to himself, and the code has been updated a lot since this time. @jtakakuwa please re-open if you're still having this issue!
