### ISSUE TITLE
[Internal] [Feature] Define Publish Directory + Params in Modules.config

### ISSUE THREAD

**Issue by kyleoconnell** [CDCgov/tostadas#96]
**What is the Feature Related To? Please Provide a Description.**

Want to move publish dirs and more of the params for individual commands like liftoff and vadr to the modules.config. This reduces the params specified in the main.nf for a given process, and also allows nextflow to handle the publishing without having to specify outdirs.

**Place an :x: in a Box that Best Matches the Feature's Importance:**
* [] **1** - Most important (absolutely integral and will not use codebase at all without it)
* [X] **2-4** - Moderate (still using codebase for other functions but is serving as a blocker for future use-cases)
* [] **5** - Least important (would like to see but there are no stringent expectations nor urgency for current/future use-cases)&nbsp;

**Any Additional Context or Information? Has There Been Any Progress Made So Far Towards this Request? Any Helpful Resources to Reference? Screenshots or Links?**

**Comment by RamiyapriyaS** [comment]
https://github.com/CDCgov/tostadas/tree/96-modules-config-refactor
