### ISSUE TITLE
[Internal] [Feature] Allow Nextflow to Handle Parameter Validation

### ISSUE THREAD

**Issue by kyleoconnell** [CDCgov/tostadas#99]
**What is the Feature Related To? Please Provide a Description.**
Nextflow has built in parameter validation. Why have the parameters validated by a separate script when this could just be included in the main workflow? 

**Place an :x: in a Box that Best Matches the Feature's Importance:**
* [] **1** - Most important (absolutely integral and will not use codebase at all without it)
* [] **2-4** - Moderate (still using codebase for other functions but is serving as a blocker for future use-cases)
* [X] **5** - Least important (would like to see but there are no stringent expectations nor urgency for current/future use-cases)&nbsp;

**Any Additional Context or Information? Has There Been Any Progress Made So Far Towards this Request? Any Helpful Resources to Reference? Screenshots or Links?**

**Comment by kyleoconnell** [comment]
Use nf-validation plugin.

**Comment by jessicarowell** [comment]
Closing - same as #143
